###
# ```{rubric} ShellCheck
# ```
# ---
# For most shell projects ShellCheck is sufficient for ensuring legible code of
# decent quality.
#
# ```{literalinclude} ./.github/workflows/shell.yml
# :caption: .github/workflows/shell.yml#name
# :language: yaml
# :start-at: "name: ShellCheck\n"
# :end-before: "###\n"
# ```
name: ShellCheck
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
###
# ```{rubric} ShellCheck Jobs
# ```
# ---
# Define the jobs that run in the ShellCheck workflow. Might like to add some
# reporting to the PR on the results from these at some point.
#
# ```{literalinclude} ./.github/workflows/shell.yml
# :caption: .github/workflows/shell.yml#jobs
# :language: yaml
# :start-at: "jobs:\n"
# ```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Test bash average
        run: |
          cd bash/10-compute-the-average;
          for i in 00 01 02 03 04 05 06; do bash average.sh < input/input${i}.txt; printf "\n"; done
      - name: Run ShellCheck with action
        uses: ludeeus/action-shellcheck@master
      - name: Run ShellCheck
        run: shellcheck --format checkstyle -a -x bash/10-compute-the-average/*.sh
